remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Time Series Machine Learning with aeon: Classification and Regression"
description: "An ECML-PKDD 2025 Demo"
